# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.2.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "${PORT}:${PORT}"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - DATABASE_AUTOMIGRATE=true
    depends_on:
      - db

volumes:
  mysql:
    driver: local
