FROM mcr.microsoft.com/devcontainers/go:0-1.20-bullseye

RUN apt-get update && apt-get install gnupg2 -y

RUN go install github.com/swaggo/swag/cmd/swag@latest

RUN git config --global --add safe.directory /workspaces

ENTRYPOINT sleep infinity 