basePath: /api/v1
definitions:
  exception.ApplicationException:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  model.UserDTO:
    properties:
      Email:
        type: string
      ID:
        type: integer
      Name:
        type: string
      Username:
        type: string
    required:
    - Email
    - ID
    - Name
    - Username
    type: object
  model.UserFormDTO:
    properties:
      Email:
        type: string
      Name:
        type: string
      Password:
        type: string
      Username:
        type: string
    required:
    - Email
    - Name
    - Password
    - Username
    type: object
info:
  contact: {}
  description: Base for SSO application written in Go
  title: Udala SSO
  version: "1.0"
paths:
  /users:
    get:
      description: Get all users in the system
      operationId: get-users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserDTO'
            type: array
      summary: Get all users
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create a new user
      operationId: create-user
      parameters:
      - description: user info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserFormDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserDTO'
      summary: Create user
  /users/{id}:
    get:
      description: Get user by ID
      operationId: get-user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/exception.ApplicationException'
      summary: Get user by ID
      tags:
      - user
swagger: "2.0"
